version: "3.2"
services:
  nginx:
    image: nginx
    container_name: joey-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  app:
    image: app
    container_name: joey-app
    restart: always
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - 4000:4000
    volumes:
      - .:/app
      - /app/node_modules
    command: /usr/local/wait-for-it.sh mongo:27017 -- npm start
    depends_on:
      - mongo
      - redis
    tty: true

  mongo:
    image: mongo
    restart: always
    container_name: joey-mongo
    volumes:
      - ~/mongodb/db:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis
    container_name: joey-cache
    ports:
      - "6379:6379"
