version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
    - "4000:4000"
    volumes:
    - ~/express-mongo/express:/app/express
    links: 
    - mongo
    tty: true
  mongo:
    container_name: mongo
    image: mongo
    ports: 
    - "27017:27017"
    tty: true